//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 12:52:30 PM EET 
//


package com.e_booking.schema.rental;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.e_booking.schema.rental package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.e_booking.schema.rental
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReserveRequestType }
     * 
     */
    public ReserveRequestType createReserveRequestType() {
        return new ReserveRequestType();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link ReserveResponseType }
     * 
     */
    public ReserveResponseType createReserveResponseType() {
        return new ReserveResponseType();
    }

    /**
     * Create an instance of {@link CancelRequestType }
     * 
     */
    public CancelRequestType createCancelRequestType() {
        return new CancelRequestType();
    }

    /**
     * Create an instance of {@link CancelResponseType }
     * 
     */
    public CancelResponseType createCancelResponseType() {
        return new CancelResponseType();
    }

    /**
     * Create an instance of {@link ListReservationsRequestType }
     * 
     */
    public ListReservationsRequestType createListReservationsRequestType() {
        return new ListReservationsRequestType();
    }

    /**
     * Create an instance of {@link ListReservationsResponseType }
     * 
     */
    public ListReservationsResponseType createListReservationsResponseType() {
        return new ListReservationsResponseType();
    }

}
