//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.04 at 02:19:46 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://e-booking.com/schema/rental", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.e_booking.schema.rental;
